#!/bin/bash
printer (){ # to see when debugging but also logs
    echo -e "$1"
    echo -e "$1" >> $log_file
}
log_file=/home/keftes/user/lectures/log/"`date +'%d-%m-%Y_%H:%M'`cleanUp.txt" 
printer "`pkill ffmpeg --echo`"
printer "`pkill zoom --echo`"
