#!/bin/bash

if [ $# -eq 0 ]
then
	echo "no args"
	exit
fi

branch=$(git rev-parse --abbrev-ref HEAD)
echo $branch
if [ "$branch" = "master" ]
then
	echo "you are on master branch"
	exit
fi
echo -e "\n\033[1mBraches:\033[0m"
git branch


echo -e "\n\n\033[1mCommit?\033[0m"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) gitcommit $1; break;;
        No ) exit;;
    esac
done

echo -e "\n\n\033[1mPush?\033[0m"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) git push origin $brach; break;;
        No ) exit;;
    esac
done

exit

