#!/bin/bash
# xclip -out -selection primary | xclip -in -selection clipboard
#echo `xclip -out -selection clipboard`

thunder=`xclip -out -selection primary`
if [[ "$thunder" =~ \.com|\.gr|\.eu|\.gov|.org ]]; then
    echo "$thunder"
    brave-browser "$thunder" &
    exit
fi

search=""

for term in $thunder; do
    search="$search%20$term"
done
#echo $search
brave-browser "http://www.google.com/search?q=$search" &
exit
