#!/bin/bash
xclip -out -selection primary | xclip -in -selection clipboard
#echo `xclip -out -selection clipboard`

thunder=`xclip -out -selection clipboard`
if [[ "$thunder" =~ \.com|\.gr|\.eu|\.gov ]]; then
    echo "$thunder"
    google-chrome "$thunder" &
    exit
fi

search=""

for term in $thunder; do
    search="$search%20$term"
done
#echo $search
google-chrome "http://www.google.com/search?q=$search" &
exit
