#!/bin/bash
printer (){ # to see when debugging but also logs
    echo -e "$1"
    echo -e "$1" >> $log_file
}
export DISPLAY=:0 # needed for crontab
google-chrome 'https://us05web.zoom.us/j/8434282909?pwd=akZnM0xpNkEwcUtIZjVXbEVwb1M4dz09&fbclid=IwAR2CkzTw58XrwaAz3ZQEh8j8arUNdiB6yaUPGLFWa_DD9Fx-ARvf3w-0jqw' &
log_file=/home/keftes/user/lectures/log/"`date +'%d-%m-%Y_%H:%M'`.txt" 
cd /home/keftes/user/lectures 
printer "at: `pwd`" 


declare -i counter=0
while [ $counter -ne 100 ] 
do
    sleep 2
    counter+=1

    printer "\n\n\ncounter: $counter" 
    export DISPLAY=:0
    printer "wmctrl:\n `wmctrl -l | grep -i "zoom"`" 
    
    export DISPLAY=:0 
    wmctrl=`wmctrl -l` 
    if [[ $wmctrl  =~ 'Zoom Meeting' ]]
    then 
        printer "\n\nFound Meeting"
        # move to first screen, focus to meeting and put fullscreen then ffmpeg
        file_name="`date +'%d-%m-%Y_%H:%M'`.mkv" 
        pipe_failed=true
        export DISPLAY=:0
        wmctrl -r "Zoom Meeting" -e 0,0,0,1280,1024 && wmctrl -a 'Zoom Meeting' && wmctrl -r 'Zoom Meeting' -b toggle,fullscreen && ffmpeg -f x11grab -s 1920x1080  -i :0.0 "$file_name" && pipe_failed=false
        if [ $pipe_failed = true ]; then # send email
            python3 /home/keftes/user/programming/python/mailer/main.py  
        fi
        break
        exit
    fi
done
python3 /home/keftes/user/programming/python/mailer/main.py   # meeting never opened

# todo put appropriate file-name
# test
# maybe sent sms