#!/bin/bash
rel=`cat /etc/os-release`
if [[ $rel =~ "18.04.1" ]]; then 
    if [ $# -eq 0 ]
    then 
        nautilus ./ &
    else
        nautilus $1 &
    fi
    exit
else
    if [ $# -eq 0 ]
    then 
        dolphin ./ &
    else
        dolphin $1 &
    fi
    exit
fi


